// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using HuePod.Nasa;
using UIKit;

using SDWebImage;

namespace HuePod.iOS
{
	public partial class ApodDetailViewController : UIViewController
	{
		public Apod Apod { get; set; }
		public ApodDetailViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			//DescriptionLabel.Text = Apod.Explanation;
			//FullImage.SetImage(new NSUrl(Apod.HdUrl));
		}
	}
}
